name: Greet command native build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Native build - ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: greet-command-linux-x64
            executable: greet

          - os: macos-latest
            artifact_name: greet-command-macos-arm64
            executable: greet

          - os: windows-latest
            artifact_name: greet-command-windows-x64
            executable: greet.exe

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: maven

      - name: Build native executable
        run: mvn -Pnative package

      - name: Upload binary
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact_name }}
          path: target/${{ matrix.executable }}
          if-no-files-found: error
